//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuclearPhysicsProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuclearPhysicsProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Hydrogen&quot;,
        ///    &quot;Symbol&quot;: &quot;H&quot;,
        ///    &quot;AtomicNumber&quot;: 1,
        ///    &quot;MassNumber&quot;: 1
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Helium&quot;,
        ///    &quot;Symbol&quot;: &quot;He&quot;,
        ///    &quot;AtomicNumber&quot;: 2,
        ///    &quot;MassNumber&quot;: 4
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Lithium&quot;,
        ///    &quot;Symbol&quot;: &quot;Li&quot;,
        ///    &quot;AtomicNumber&quot;: 3,
        ///    &quot;MassNumber&quot;: 7
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Beryllium&quot;,
        ///    &quot;Symbol&quot;: &quot;Be&quot;,
        ///    &quot;AtomicNumber&quot;: 4,
        ///    &quot;MassNumber&quot;: 9
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Boron&quot;,
        ///    &quot;Symbol&quot;: &quot;B&quot;,
        ///    &quot;AtomicNumber&quot;: 5,
        ///    &quot;MassNumber&quot;: 11
        ///  },
        ///  {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Symbol&quot;: &quot;H&quot;,
        ///    &quot;Isotopes&quot;: [
        ///      {
        ///        &quot;Symbol&quot;: &quot;H&quot;,
        ///        &quot;MassNumber&quot;: 1,
        ///        &quot;HalfLife&quot;: &quot;&quot;,
        ///        &quot;Decays&quot;: [
        ///
        ///        ]
        ///      },
        ///      {
        ///        &quot;Symbol&quot;: &quot;H&quot;,
        ///        &quot;MassNumber&quot;: 2,
        ///        &quot;HalfLife&quot;: &quot;&quot;,
        ///        &quot;Decays&quot;: [
        ///
        ///        ]
        ///      },
        ///      {
        ///        &quot;Symbol&quot;: &quot;H&quot;,
        ///        &quot;MassNumber&quot;: 3,
        ///        &quot;HalfLife&quot;: &quot;388789632&quot;,
        ///        &quot;Decays&quot;: [
        ///          {
        ///            &quot;Type&quot;: &quot;Beta-&quot;,
        ///            &quot;Product&quot;: &quot;He&quot;,
        ///            &quot;AtomicNum [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Isotopes {
            get {
                return ResourceManager.GetString("Isotopes", resourceCulture);
            }
        }
    }
}
